!ServerConfiguration
hashing_algorithm: SHA-1
upload_directory: ../../upload

database_configuration: !DatabaseConfiguration
  driver: sqlite
  database: ../../storage/server.db
  echo: true

importer_configuration: !ImporterConfiguration
  import_script_command: bin/directory_import
  collection_name: LCP
  collection_type: LCP
  data_source_name: data_source_1